# --- !Ups

CREATE TABLE "EMAIL" ("EMAIL" VARCHAR PRIMARY KEY, "JOINDATE" timestamp NOT NULL);

CREATE TABLE "ORDERS" ("ID" serial NOT NULL PRIMARY KEY, "EMAIL" VARCHAR NOT NULL, "AMOUNT" integer NOT NULL, "AMOUNTPAID" integer NOT NULL);

CREATE TABLE "TICKETS"("ID" serial NOT NULL PRIMARY KEY, "FIRSTNAME" VARCHAR NOT NULL, "LASTNAME" VARCHAR NOT NULL, "ORDERID" integer NOT NULL REFERENCES "ORDERS"("ID"));

# --- !Downs

DROP TABLE "EMAIL";

DROP TABLE "ORDERS";

DROP TABLE "TICKETS";