# --- !Ups

CREATE TABLE "EMAIL" ("EMAIL" VARCHAR PRIMARY KEY, "JOINDATE" timestamp NOT NULL);

CREATE TABLE "TICKETS"("ID" serial NOT NULL PRIMARY KEY, "FIRSTNAME" VARCHAR NOT NULL, "LASTNAME" VARCHAR NOT NULL, "EMAIL" VARCHAR NOT NULL, "DEPOSITONLY" BOOLEAN NOT NULL, "PAYBY" timestamp NOT NULL);

# --- !Downs

DROP TABLE "EMAIL";

DROP TABLE "TICKETS";