# --- !Ups

CREATE TABLE "EMAIL" ("EMAIL" VARCHAR PRIMARY KEY, "JOINDATE" timestamp NOT NULL);

CREATE TABLE "WAIT" ("EMAIL" VARCHAR PRIMARY KEY, "JOINDATE" timestamp NOT NULL);

CREATE TABLE "TICKET"("ID" serial NOT NULL PRIMARY KEY, "FIRSTNAME" VARCHAR NOT NULL, "LASTNAME" VARCHAR NOT NULL, "EMAIL" VARCHAR NOT NULL, "DEPOSITTRANSACTION" VARCHAR, "FINALTRANSACTION" VARCHAR, "ISDINING" BOOLEAN NOT NULL DEFAULT FALSE, "DONATION" INTEGER DEFAULT 0, "UPGRADETRANSACTION" VARCHAR);

# --- !Downs

DROP TABLE "EMAIL";

DROP TABLE "TICKET";